# Generated by Django 4.0.1 on 2022-03-19 05:02

from django.db import migrations, models
import sap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='fullname')),
                ('gender', models.CharField(blank=True, max_length=255, null=True, verbose_name='gender')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='occupation')),
                ('monthly_salary', models.CharField(blank=True, max_length=255, null=True, verbose_name='monthly_salary')),
                ('type_of_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='type_of_id')),
                ('id_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='id_number')),
                ('cellphone', models.CharField(blank=True, max_length=255, null=True, verbose_name='cellphone')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='workplace')),
                ('sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='sector')),
                ('health_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='health_condition')),
                ('family_member', models.CharField(blank=True, max_length=500, null=True, verbose_name='family_member')),
                ('image', models.ImageField(default='uploads/SAP.png', upload_to=sap.models.nameFile, verbose_name='image')),
            ],
        ),
    ]
