# Generated by Django 4.0.1 on 2022-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0002_sap_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='user_id'),
        ),
    ]
