# Generated by Django 4.0.1 on 2022-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0003_sap_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sap',
            name='fullname',
        ),
        migrations.AddField(
            model_name='sap',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='sap',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname'),
        ),
    ]
