# Generated by Django 4.0.1 on 2022-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0004_remove_sap_fullname_sap_firstname_sap_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
