# Generated by Django 4.0.1 on 2022-05-21 14:34

from django.db import migrations, models
import sap.models


class Migration(migrations.Migration):

    dependencies = [
        ('sap', '0007_sap_mop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sap',
            name='image1',
            field=models.ImageField(default='uploads/SAP.png', upload_to=sap.models.nameFile, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='sap',
            name='image2',
            field=models.ImageField(default='uploads/SAP.png', upload_to=sap.models.nameFile, verbose_name='image2'),
        ),
    ]
