# Generated by Django 4.0.1 on 2022-03-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='middlename'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='beneficiaries',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
    ]
