# Generated by Django 4.0.1 on 2022-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiaries_lastname_beneficiaries_middlename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
