# Generated by Django 4.0.1 on 2022-03-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_beneficiaries_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id'),
        ),
    ]
