# Generated by Django 4.0.1 on 2022-05-15 04:43

import beneficiaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0008_beneficiaries_mop'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='image',
            field=models.ImageField(default='uploads/Beneficiaries.png', upload_to=beneficiaries.models.nameFile, verbose_name='image'),
        ),
    ]
