# Generated by Django 4.0.1 on 2022-05-21 14:34

import beneficiaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0009_beneficiaries_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='image1',
            field=models.ImageField(default='uploads/Beneficiaries.png', upload_to=beneficiaries.models.nameFile, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='image2',
            field=models.ImageField(default='uploads/Beneficiaries.png', upload_to=beneficiaries.models.nameFile, verbose_name='image2'),
        ),
    ]
