# Generated by Django 4.0.1 on 2022-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('case_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='case_id')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
