# Generated by Django 4.0.1 on 2022-05-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Barangay',
            new_name='Referral',
        ),
    ]
