# Generated by Django 4.0.1 on 2022-05-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0002_ps_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps',
            name='mop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mop'),
        ),
    ]
