# Generated by Django 4.0.1 on 2022-05-21 14:34

from django.db import migrations, models
import ps.models


class Migration(migrations.Migration):

    dependencies = [
        ('ps', '0003_ps_mop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps',
            name='image1',
            field=models.ImageField(default='uploads/PS.png', upload_to=ps.models.nameFile, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='ps',
            name='image2',
            field=models.ImageField(default='uploads/PS.png', upload_to=ps.models.nameFile, verbose_name='image2'),
        ),
    ]
