# Generated by Django 4.0.1 on 2022-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id'),
        ),
    ]
