# Generated by Django 4.0.1 on 2022-03-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='remarks'),
        ),
    ]
