# Generated by Django 4.0.1 on 2022-05-21 14:34

from django.db import migrations, models
import donate.models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_alter_donate_firstname_alter_donate_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='image1',
            field=models.ImageField(default='uploads/Donate.png', upload_to=donate.models.nameFile, verbose_name='image1'),
        ),
        migrations.AddField(
            model_name='donate',
            name='image2',
            field=models.ImageField(default='uploads/Donate.png', upload_to=donate.models.nameFile, verbose_name='image2'),
        ),
    ]
