# Generated by Django 4.0.1 on 2022-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_cases_address_cases_age_cases_attainment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='intervention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='intervention'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_address'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_age',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_age'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_name'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_nickname'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_occupation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_occupation'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_relation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_relation'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_sex',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_sex'),
        ),
        migrations.AddField(
            model_name='cases',
            name='perpetrator_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='perpetrator_status'),
        ),
        migrations.AddField(
            model_name='cases',
            name='referral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='referral'),
        ),
        migrations.AddField(
            model_name='cases',
            name='social_worker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='social_worker'),
        ),
        migrations.AddField(
            model_name='cases',
            name='source_of_referral',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='source_of_referral'),
        ),
    ]
