# Generated by Django 4.0.1 on 2022-03-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_cases_intervention_cases_perpetrator_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='case_category'),
        ),
    ]
